var LISTINGS_DATA = [
  {
    id: 'house-001',
    title: 'Two Bedroom Apartment',
    location: 'Westlands, Nairobi',
    estate: 'westlands',
    type: 'twoBedroom',
    price: 45000,
    deposit: 90000,
    beds: 2,
    baths: 1,
    size: '85 sqm',
    verified: true,
    inspected: true,
    isNew: false,
    images: [
      'images/house1.jpg',
      'images/house1.jpg',
      'images/house1.jpg',
      'images/house1.jpg',
      'images/house1.jpg'
    ],
    description: 'A well-maintained two bedroom apartment in the heart of Westlands. The apartment features spacious rooms, reliable borehole water supply, and 24-hour security. Located minutes from ABC Place and Sarit Centre, with easy access to public transport along Waiyaki Way.',
    amenities: ['Parking', 'Borehole water', '24hr security', 'DSTV dish', 'Prepaid electricity', 'Intercom'],
    agent: { name: 'James Maina', phone: '254712000001' },
    landlordPhone: '254712000001',
    paymentTerms: 'Monthly'
  },
  {
    id: 'house-002',
    title: 'Two Bedroom Apartment',
    location: 'Kilimani, Nairobi',
    estate: 'kilimani',
    type: 'twoBedroom',
    price: 50000,
    deposit: 100000,
    beds: 2,
    baths: 1,
    size: '90 sqm',
    verified: true,
    inspected: false,
    isNew: true,
    images: [
      'images/house2.jpg',
      'images/house2.jpg',
      'images/house2.jpg',
      'images/house2.jpg',
      'images/house2.jpg'
    ],
    description: 'Brand new two bedroom apartment in Kilimani, walking distance from Yaya Centre and Junction Mall. Features modern finishes throughout, a lift, fibre-ready infrastructure, and covered parking. Water is supplied from a dedicated borehole with no interruptions.',
    amenities: ['Lift', 'Fibre-ready', 'Borehole water', 'Parking', 'CCTV', 'Backup generator'],
    agent: { name: 'Phillip Otieno', phone: '254712000002' },
    landlordPhone: '254712000002',
    paymentTerms: 'Monthly'
  },
  {
    id: 'house-003',
    title: 'Three Bedroom Apartment',
    location: 'Thindigua, Kiambu',
    estate: 'thindigua kiambu',
    type: 'threeBedroom',
    price: 75000,
    deposit: 150000,
    beds: 3,
    baths: 2,
    size: '130 sqm',
    verified: true,
    inspected: true,
    isNew: false,
    images: [
      'images/house3.jpg',
      'images/house3.jpg',
      'images/house3.jpg',
      'images/house3.jpg',
      'images/house3.jpg'
    ],
    description: 'Spacious three bedroom apartment in the quiet Thindigua area along Kiambu Road. Ideal for families, the unit features two full bathrooms, a large open-plan kitchen and living area, ample storage, and a balcony. The compound has borehole water, a generator, and is gated with a guard.',
    amenities: ['Balcony', 'Borehole water', 'Backup generator', '24hr security', 'Parking', 'Garden'],
    agent: { name: 'James Maina', phone: '254712000001' },
    landlordPhone: '254712000001',
    paymentTerms: 'Monthly'
  },
  {
    id: 'house-004',
    title: 'Four Bedroom House',
    location: 'Runda, Kiambu',
    estate: 'runda kiambu',
    type: 'fourBedroom',
    price: 250000,
    deposit: 500000,
    beds: 4,
    baths: 4,
    size: '300 sqm',
    verified: true,
    inspected: false,
    isNew: true,
    images: [
      'images/house4.jpg',
      'images/house4.jpg',
      'images/house4.jpg',
      'images/house4.jpg',
      'images/house4.jpg'
    ],
    description: 'Stunning four bedroom family home in the prestigious Runda estate. The property sits on a generous plot with a landscaped garden, a two-car garage, and a separate staff quarters. Inside features high ceilings, a modern kitchen, an en-suite master bedroom, and a large family lounge. Solar water heating included.',
    amenities: ['Swimming pool', 'Garden', 'Staff quarters', '2-car garage', 'Solar water heating', 'CCTV', 'Electric fence', 'Borehole'],
    agent: { name: 'Sarah Wairimu', phone: '254712000003' },
    landlordPhone: '254712000003',
    paymentTerms: 'Monthly'
  },
  {
    id: 'house-005',
    title: 'Three Bedroom Villa',
    location: 'Hurlingham, Nairobi',
    estate: 'hurlingham nairobi',
    type: 'threeBedroom',
    price: 200000,
    deposit: 400000,
    beds: 3,
    baths: 3,
    size: '210 sqm',
    verified: true,
    inspected: false,
    isNew: true,
    images: [
      'images/house5.jpg',
      'images/house5.jpg',
      'images/house5.jpg',
      'images/house5.jpg',
      'images/house5.jpg'
    ],
    description: 'Elegant three bedroom villa in Hurlingham, minutes from Kilimani and the CBD. Each bedroom has its own en-suite bathroom. The property features a private courtyard, a modern fitted kitchen, and a rooftop terrace with city views. Ideal for professionals or small families seeking privacy and style.',
    amenities: ['Rooftop terrace', 'En-suite bathrooms', 'Private courtyard', 'Fibre internet', 'Parking', 'Intercom', 'Prepaid electricity'],
    agent: { name: 'Phillip Otieno', phone: '254712000002' },
    landlordPhone: '254712000002',
    paymentTerms: 'Monthly'
  },
  {
    id: 'house-006',
    title: 'Four Bedroom Villa',
    location: 'Karen, Nairobi',
    estate: 'karen nairobi',
    type: 'fourBedroom',
    price: 350000,
    deposit: 700000,
    beds: 4,
    baths: 4,
    size: '380 sqm',
    verified: true,
    inspected: true,
    isNew: false,
    images: [
      'images/house6.jpg',
      'images/house6.jpg',
      'images/house6.jpg',
      'images/house6.jpg',
      'images/house6.jpg'
    ],
    description: 'Magnificent four bedroom villa in Karen set on over half an acre of mature gardens. The property features a heated swimming pool, guest house, three-car garage, and a fully equipped open-plan kitchen. The master suite has a walk-in wardrobe and a private balcony overlooking the garden. Security includes CCTV, electric fence, and a 24-hour guard.',
    amenities: ['Swimming pool', 'Guest house', '3-car garage', 'Heated pool', 'Electric fence', 'CCTV', '24hr guard', 'Borehole', 'Solar backup', 'Garden'],
    agent: { name: 'Eric Karanja', phone: '254712000004' },
    landlordPhone: '254712000004',
    paymentTerms: 'Monthly'
  }
];